##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. Use of this
## source code is governed by an MIT-style license that can be found in the
## LICENSE file.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: example

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter
  df_debouncer:
    path: ../

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# -----------------------------------------------------------------------------

flutter:
